### ISSUE TITLE
islandora_themekey and newspaper SP

### ISSUE THREAD

**Issue by petermacdonald** [mjordan/islandora_themekey#2]
I had a great time setting up different themes for different collection objects and items with isMemberOfCollection relationships using this module, but unfortunately, whenever the islandora_themekey module is enabled my newspaper objects stop working -- even if that newspaper and its collection are NOT directly configured for a theme by the islandora_themekey module.

The symptom is that the newspaper page images never display and the watchdog log shows errors like this:

User    Anonymous (not verified)
Location    http://lis.hamilton.edu/islandora/object/hamLibCom%3A4796/datastream/JP2/view?token=20a07124f9742a870ea265977bab247b76c7958c33296c10157c344d957855ac
Referrer  
Message RepositoryException: Unauthorized in RepositoryConnection->parseFedoraExceptions() (line 230 of /home/lisham/public_html/sites/all/libraries/tuque/RepositoryConnection.php).

When I DISable the islandora_themekey module, the newspapers return to their normal behavior.

I've played with the module's AJAX settings, but that didn't fix anything.

I'd like to use this module, but I can't run my server with the module enabled.

Peter

**Comment by mjordan** [comment]
I'll take a look at this. Thanks for reporting it.

**Comment by mjordan** [comment]
@petermacdonald I can't replicate this issue. I wonder if it matters what version of the newspaper SP you are using. I'm running HEAD (last commit 51a676c0c57e91e97fdfa5062e795265b12c6162).

But, newspaper pages (and book pages) are not members of a collection. Their parent issues/books are. So at the moment using the ismemberofocollection themekey property is not going to switch themes for pages anyway. I'll open a new feature issue to make ismemberofcollection apply to pages.

In the meantime, can you let me know what version or if on HEAD what the last commit is of the newspaper SP you are using?

**Comment by mjordan** [comment]
Issue opened at #4 (update: this feature is now in place - newspaper issues, page, and book pages respect is_member_of_collection ThemeKey rules).

If your newspapers all share a namespace, you can also create themekey rules based on that.

**Comment by mjordan** [comment]
@petermacdonald Note that today, July 19, I changed the condition name of ismemberofcollection to is_member_of_collection to improve readibility in the long list of conditions. You will need to update any
 rules you created prior to the change to use the new condition name (is_member_of_collection). I apologize for this backward compatibility breaking change but now that Islandora Theme
Key supports multiple conditions, I thought it was worth making their names more readable before we add more.

**Comment by mjordan** [comment]
@petermacdonald Can I close this issue?

**Comment by petermacdonald** [comment]
Ok with me. Thx

Peter

On Tuesday, November 3, 2015, Mark Jordan notifications@github.com wrote:

> @petermacdonald https://github.com/petermacdonald Can I close this
> issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mjordan/islandora_themekey/issues/2#issuecomment-153253797
> .

## 

Peter MacDonald,
Library Information Systems Specialist
Hamilton College Library
Clinton, New York
315 859-4493
pmacdona-hamilton (Skype)

**Comment by nhart** [comment]
@mjordan I think this is still an issue when XACML is involved.
