### ISSUE TITLE
Improve implementation of ThemeKey hooks

### ISSUE THREAD

**Issue by mkalkbrenner** [mjordan/islandora_themekey#6]
I don't have any knowledge about Islandora. But the implementation of function islandora_themekey_themekey_global() seems inefficient to me.
hook_themekey_global() is only meant for _really_ simple properties, because they're populated on every page request.
But the somehow complex logic in your implementation should be moved to mapping functions which are only executed on demand.

https://www.drupal.org/node/2536404

**Comment by mjordan** [comment]
@mkalkbrenner Thanks, I agree. I implemented hook_themekey_global() to get things going and prove we could access Islandora object (which are not nodes) properties. I'll look into replacing that hook with mapping functions.

**Comment by mjordan** [comment]
is_member_of_collection now uses a mapping function.
